name: solvers-test

channels:
  - conda-forge
  - pytorch
  - nvidia

dependencies:
  - numpy=1.25.*
  - jupyter
  - scipy=1.12.0
  - pydiso=0.0.5
  - matplotlib=3.8.*
  - python=3.11.*
  - pytorch=2.1.*
  - pytorch-cuda=11.8
  - geoana=0.5.0
  - discretize=0.10.0
  - SimPEG=0.21.1
  - cupy=13.1.0

